module.exports = {
  PAGE_SIZE: 8,
  OK: "OK",
  FAIL: "FAIL",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  PAYPAL: "PAYPAL",
  COD: "COD",
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  DONE: "DONE",
  CANCELED: "CANCELED",
  OVERSEA: "OVERSEA",
  INLAND: "INLAND",
  MALE: "MALE",
  FEMALE: "FEMALE",
  BISEXUAL: "BISEXUAL",
  SUPER: 0,
  ADMIN: 1,
  USER: 2,
  wsConnectionName: {
    NOTIFICATION: "notification",
  },
  wsCommands: {
    PUSH_MESSAGE: "PUSH_MESSAGE",
  },
};
